DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `salt` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `active` TINYINT(1) UNSIGNED NOT NULL DEFAULT '1',
  `created` INT(11) UNSIGNED NOT NULL,
  `deleted` INT(11) UNSIGNED DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
